### ISSUE TITLE
Could not launch “Diffusion”

### ISSUE THREAD

**Issue by berkbirkan** [huggingface/swift-coreml-diffusers#10]
hello, when i was trying to run this program on my m1 chip mac, i got error.  how can i solve this error ? help me please.
error message : 
Could not launch “Diffusion”
The app is incompatible with the current version of macOS. Please check the app's deployment target.

error screenshot:
<img width="1383" alt="errorss1" src="https://user-images.githubusercontent.com/24484253/211212119-09a212c1-d291-449c-a4f7-8c938f8dc7bf.png">

about my mac screenshot : 
<img width="296" alt="errorss2" src="https://user-images.githubusercontent.com/24484253/211212141-87ca1f1d-2b02-4206-b22f-f8d909d29f74.png">

**Comment by julien-c** [comment]
You need `mac OS 13.1 +` to run it!

Hope this helps

**Comment by berkbirkan** [comment]
Ok , i will upgrade my macOS. But there is something i dont understand : Development target was not 13.1+. Why i need to upgrade my system ? 

> You need `mac OS 13.1 +` to run it!
> 
> Hope this helps

**Comment by pcuenca** [comment]
Hi @berkbirkan, it's the _deployment_ target what's set to `13.1`. You can compile if you have the SDK, but running requires bug fixes in the Core ML backend that were released in 13.1.
