### ISSUE TITLE
Model occasionally redownloaded on startup

### ISSUE THREAD

**Issue by pcuenca** [huggingface/swift-coreml-diffusers#16]
Reported by https://twitter.com/andrekerygma in Twitter, also mentioned by @osanseviero.

**Comment by iandol** [comment]
Can confirm this bug. Where are models supposed to be stored, somewhere in `~/Library/Containers`?

**Comment by pcuenca** [comment]
Yes, it's `~/Library/Containers/com.huggingface.Diffusers/Data/Library/Application Support/hf-diffusion-models`.

(If you download the code and compile it yourself, then it will be `~/Library/Application Support/hf-diffusion-models` for `Debug` builds).
