### ISSUE TITLE
Safety checker triggered

### ISSUE THREAD

**Issue by Luke-qpla** [huggingface/swift-coreml-diffusers#17]
Hello! I'm getting an error when trying any prompt on any model, even if I change the seed value.
Any idea on how to fix it?
Thank you!

![FnyTeMTacAAe5Ge](https://user-images.githubusercontent.com/122469888/215708259-213242f9-0ad3-4989-a027-5212b9fbc6f0.jpeg)

![スクリーンショット 2023-01-31 17 22 03](https://user-images.githubusercontent.com/122469888/215708038-1caf4c33-9154-48cb-9c3b-e04eec6c5216.png)

**Comment by pcuenca** [comment]
Thank you for the details @Luke-qpla! Unfortunately, I think that GPU does not have enough memory to run Stable Diffusion. We'll provide a better error message in these situations.
