### ISSUE TITLE
Can't build project on iPhone

### ISSUE THREAD

**Issue by lishicheng1996** [huggingface/swift-coreml-diffusers#26]
Hi, I can't build this project on iPhone, with serveral errors.  Not change any code. Is there a bug, or my project setting is not correct?
<img width="492" alt="Screenshot 2023-02-09 at 20 04 52" src="https://user-images.githubusercontent.com/43111799/217807974-fcc8018e-b6db-44dd-a5e0-5d21714b6a3c.png">

**Comment by pcuenca** [comment]
You are right, I made some changes yesterday intended for the macOS version but did not update the iOS code. I'll fix it today. Thanks a lot!

**Comment by pcuenca** [comment]
@lishicheng1996 can you please try now?

**Comment by lishicheng1996** [comment]
> @lishicheng1996 can you please try now?

Build success now. Thank you!
