### ISSUE TITLE
How to run this as a newb? 

### ISSUE THREAD

**Issue by creamlabsAI** [huggingface/swift-coreml-diffusers#33]
I'm a coding newbie, so this may be sort of a dumb question. How do I run this on my M1 Max 64GB? Downloaded the package and also through GitHub Desktop. As far as I understand, I need to compile it but cannot find the right tutorial to help me with this. 

Any help would be much appreciated.

**Comment by pcuenca** [comment]
Hi @creamlabsAI! The compiled app is available in the Mac App Store: https://apps.apple.com/app/diffusers/id1666309574. I'll update the README file :)

If you want to explore the code, then you need Xcode, the development IDE provided by Apple.

**Comment by creamlabsAI** [comment]
Thank you for the fast reply. Yes, that would be helpful ;)

**Comment by pcuenca** [comment]
I just updated the README. Thanks for the feedback, @creamlabsAI!

**Comment by parth7326** [comment]
I want to run this app on iOS? Can I build it in macOS 13.1? Also is there any other easy way I can run it on IOS
