### ISSUE TITLE
Denoising strength

### ISSUE THREAD

**Issue by alelordelo** [huggingface/swift-coreml-diffusers#38]
Thanks for sharing this great repo!

Is it possible to control Denoising strength? I know by default the app doesn’t support, but does the coreML SD package support it?

**Comment by pcuenca** [comment]
Hi @alelordelo! What do you mean exactly by denoising strength? I've seen that term in the context of image-to-image generation, but so far we are doing text-to-image. Would you mind clarifying a bit? :)

**Comment by alelordelo** [comment]
Hi Pedro,Yup, that is a parameter that affects heavily image to image generation.So if there is only text to image now, no need to add it.Thanks!Sent from my iPhoneOn 1 Mar 2023, at 20:12, Pedro Cuenca ***@***.***> wrote:﻿
Hi @alelordelo! What do you mean exactly by denoising strength? I've seen that term in the context of image-to-image generation, but so far we are doing text-to-image. Would you mind clarifying a bit? :)

**Comment by pcuenca** [comment]
Cool, understood! This repo does not have image to image (yet), but it was recently added to Apple's one (which is a dependency here). See here for the strength parameter: https://github.com/apple/ml-stable-diffusion/blob/main/swift/StableDiffusion/pipeline/StableDiffusionPipeline.Configuration.swift#L27

**Comment by alelordelo** [comment]
Ah, nice! Thanks for pointing that!Sent from my iPhoneOn 2 Mar 2023, at 10:18, Pedro Cuenca ***@***.***> wrote:﻿
Cool, understood! This repo does not have image to image (yet), but it was recently added to Apple's one (which is a dependency here). See here for the strength parameter: https://github.com/apple/ml-stable-diffusion/blob/main/swift/StableDiffusion/pipeline/StableDiffusionPipeline.Configuration.swift#L27
