### ISSUE TITLE
The GUI is different from Readme

### ISSUE THREAD

**Issue by learningpro** [huggingface/swift-coreml-diffusers#46]
![screenshot-20230424-223733](https://user-images.githubusercontent.com/1081377/234030021-74793d15-01b2-4624-ad71-7d7306c9a9f2.png)

Without doing any code change after cloning the code, it runs successfully, but not the same appearance as shown in Readme, I didn't find the left part.

Could anyone help on this?

Much appreciated

**Comment by stuartjmoore** [comment]
That’s the iOS version running on your Mac. Switch the scheme to “Diffuision-macOS”.
