### ISSUE TITLE
The model file links to huggingface.co/pcuenq are broken

### ISSUE THREAD

**Issue by mikowals** [huggingface/swift-coreml-diffusers#47]
<img width="1512" alt="Screenshot 2023-05-09 at 7 59 29 pm" src="https://user-images.githubusercontent.com/1331470/237063276-10747e64-397f-48fd-ad17-88e4dafd41ea.png">
<img width="1512" alt="Screenshot 2023-05-09 at 7 59 05 pm" src="https://user-images.githubusercontent.com/1331470/237063308-1e845d0e-dc0d-4e2d-a16c-ed0141f63825.png">

**Comment by pcuenca** [comment]
The repos have been restored now, closing this issue :)
