### ISSUE TITLE
App doesn't run on macOS

### ISSUE THREAD

**Issue by opendiff** [huggingface/swift-coreml-diffusers#5]
### No releases or CI 

Have you thought about creating a GitHub Actions CI job to build the app, run the tests, and publish releases to GitHub?

### Fails to run on macOS

The app doesn't run on macOS 13.1 (22C65) with Xcode 14.1 out of the box. It works if I run in an iPad simulator.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/121370396/209457116-6598d653-cede-499d-bb16-1fed9c8f1c9b.png">

I believe the error is due to code signing, since the huggingface credentials are hard coded.

### Fails to build with CLI

I'm also seeing compile errors when trying to build the app from the CLI. When building from Xcode, the build phase succeeds however launch fails.

```
$ xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

/swift-coreml-diffusers/Diffusion/Pipeline/Pipeline.swift:13:8: error: no such module 'StableDiffusion'
import StableDiffusion
       ^

** BUILD FAILED **
```

Edit: I successfully built and ran the app using this command:

```
xcodebuild clean build -scheme Diffusion CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
```

**Comment by pcuenca** [comment]
Should be fixed by https://github.com/huggingface/swift-coreml-diffusers/commit/7e9956725b892992c0ee6ce41d86b6fffc38df3c.
