### ISSUE TITLE
Controls GUI Not Showing

### ISSUE THREAD

**Issue by beezbo** [huggingface/swift-coreml-diffusers#71]
My GUI is more basic than the one in the readme. Did I not build it correctly or do I need to be on macOS 14? I would like to run the SD XL models. I am running macOS 13.5 and guessing I could run the non-quantized model even if it would be really slow.

<img width="712" alt="image" src="https://github.com/huggingface/swift-coreml-diffusers/assets/140455770/8fa22121-5cb1-4e19-9876-4aca819a64b6">

**Comment by ynagatomo** [comment]
Please use the `Diffusion-macOS` scheme.
<img width="888" alt="Screenshot 2023-07-31 at 16 04 31" src="https://github.com/huggingface/swift-coreml-diffusers/assets/66309582/584f4565-0b80-42cc-ac4c-8aa01f0d825a">

**Comment by pcuenca** [comment]
That's exactly right, you need to use the mac target. However, the XL model requires iOS 14. In this app, you could copy this line in the `else` to have it show up in the UI: https://github.com/huggingface/swift-coreml-diffusers/blob/e5f9a6578d735e7f2bf87a7114a22db45d23b4d6/Diffusion/Common/ModelInfo.swift#L200

However, the XL pipeline is only supported in macOS 14 in `apple/ml-stable-diffusion`, so you'd need to make modifications there too.

**Comment by beezbo** [comment]
Thanks, that solved my issue.
