### ISSUE TITLE
Cound not download SDXL model by default options.

### ISSUE THREAD

**Issue by TimYao18** [huggingface/swift-coreml-diffusers#73]
Both SDXL models are not found and cannot download.
SDXL base: 
`https://huggingface.co/apple/coreml-stable-diffusion-xl-base/resolve/main/coreml-stable-diffusion-xl-base_split_einsum_compiled.zip` 
SDXL base(4.5 bit):
`https://huggingface.co/apple/coreml-stable-diffusion-mixed-bit-palettization/resolve/main/coreml-stable-diffusion-mixed-bit-palettization_split_einsum_compiled.zip`
are not found.

I found the file on HuggingFace is only original one:
`https://huggingface.co/apple/coreml-stable-diffusion-xl-base/resolve/main/coreml-stable-diffusion-xl-base_original_compiled.zip`

**Comment by DigitalSolomon** [comment]
Not sure if this is related, but I'm getting "Pipeline loading error" when selecting either of the SDXL models.

Xcode Version 15.0 beta 5 (15A5209g)
macOS 14.0 Beta (23A5301h)

<img width="908" alt="Screenshot 2023-07-31 at 10 18 38 PM" src="https://github.com/huggingface/swift-coreml-diffusers/assets/6760930/cdb5c557-ea32-4cce-b0fd-7bf411c54016">

**Comment by ynagatomo** [comment]
please select Advanced - [v] GPU

**Comment by DigitalSolomon** [comment]
@TimYao18 did this work for you? Selecting `Advanced - [v] GPU` does use the correct link, but then it fails trying to resolve the path to `merges.txt` (the actual directory structure has the file in a `/compiled` subdirectory):

```
Failed to create tokenizer: Error Domain=NSCocoaErrorDomain Code=260 "The file “merges.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/userName/Library/Application Support/hf-diffusion-models/coreml-stable-diffusion-mixed-bit-palettization_split_einsum_compiled/merges.txt, NSUnderlyingError=0x60000050da70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Failed to create tokenizer: Error Domain=NSCocoaErrorDomain Code=260 "The file “merges.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/userName/Library/Application Support/hf-diffusion-models/coreml-stable-diffusion-mixed-bit-palettization_split_einsum_compiled/merges.txt, NSUnderlyingError=0x60000050d9b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Could not load model, error: Error Domain=NSCocoaErrorDomain Code=260 "The file “merges.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/userName/Library/Application Support/hf-diffusion-models/coreml-stable-diffusion-mixed-bit-palettization_original_compiled/merges.txt, NSUnderlyingError=0x6000004a1a40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Failed to create tokenizer: Error Domain=NSCocoaErrorDomain Code=260 "The file “merges.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/userName/Library/Application Support/hf-diffusion-models/coreml-stable-diffusion-mixed-bit-palettization_split_einsum_compiled/merges.txt, NSUnderlyingError=0x600000486190 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Failed to create tokenizer: Error Domain=NSCocoaErrorDomain Code=260 "The file “merges.txt” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/userName/Library/Application Support/hf-diffusion-models/coreml-stable-diffusion-mixed-bit-palettization_split_einsum_compiled/merges.txt, NSUnderlyingError=0x600000486280 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Reusing same model ModelInfo(modelId: "apple/coreml-stable-diffusion-mixed-bit-palettization", modelVersion: "Stable Diffusion XL base [4.5 bit]", originalAttentionSuffix: "original_compiled", splitAttentionSuffix: "split_einsum_compiled", splitAttentionV2Suffix: "split_einsum_v2_compiled", supportsEncoder: true, supportsAttentionV2: false, quantized: true, isXL: true) with units MLComputeUnits(rawValue: 1)
```

**Comment by ynagatomo** [comment]
please check issue 68, you need to move the files to their parent folder.

**Comment by TimYao18** [comment]
@DigitalSolomon I select GPU and it is downloading. So I think this issue "Could not download" is solved. 

It cannot run default downloaded SDXL model, yes.
I run it using my modified "reveal in Finder" option that can use custom path model and control net.

**Comment by DigitalSolomon** [comment]
Ah, okay. I've noticed too that the structure seems to be different depending if you choose `SDXL Base` or `SDXL base [4.5bit]`. It seems the 4.5bit has the folder structure issue, whereas the other one doesn't.
