### ISSUE TITLE
Missing sidebar in app

### ISSUE THREAD

**Issue by gwinbush** [huggingface/swift-coreml-diffusers#75]
Hello 👋 
When I try to build and run this project in XCode locally, **I am not seeing the sidebar in the application**.

Apologies if this is a stupid question -- I am quite new to Swift development. But am I missing something or is this a bug?

Additional info:
- 2021 MacBook Pro, M1 Max
- macOS Sonoma 14.0 (beta)
- XCode 15.0 (beta 5)

### Example
<img width="1402" alt="image" src="https://github.com/huggingface/swift-coreml-diffusers/assets/16084853/9f089f15-c791-4b2b-9726-02693ef836ca">

### Expected
<img width="361" alt="image" src="https://github.com/huggingface/swift-coreml-diffusers/assets/16084853/26d4bf31-de41-47ae-b178-d4330ad1e8a6">

**Comment by dolmere** [comment]
Common question. See https://github.com/huggingface/swift-coreml-diffusers/issues/71

**Comment by gwinbush** [comment]
Ah, thank you very much @dolmere. Closing the issue
