### ISSUE TITLE
Mac Catalyst error:: 'PixelBuffer' is not a member type of enum 'Accelerate.vImage'

### ISSUE THREAD

**Issue by liamwalsh** [huggingface/swift-coreml-diffusers#9]
I get the following error when choosing to build for the Mac using Catalyst, either Rosetta or not 

`/SourcePackages/checkouts/ml-stable-diffusion/swift/StableDiffusion/pipeline/Decoder.swift:80:40: error build: 'PixelBuffer' is not a member type of enum 'Accelerate.vImage'`

Building on device for iPad does work, however - any ideas how to run on a Mac? 

Mac OS 13.1 - iOS 16.1 Xcode 14.0

**Comment by pcuenca** [comment]
Hi @liamwalsh, thanks for writing! I think you might need Xcode 14.2, could you please try to upgrade and see if that works?

**Comment by liamwalsh** [comment]
Aha, right you are - 14.2 is all good thanks!
