### ISSUE TITLE
No option for Stable Diffusion 3 Medium

### ISSUE THREAD

**Issue by opkins** [huggingface/swift-coreml-diffusers#97]
Only for 1.4, 1.5, 2.0, .2.1

Am I missing something?

**Comment by pcuenca** [comment]
The PR is here: https://github.com/huggingface/swift-coreml-diffusers/pull/96

**Comment by opkins** [comment]
Thanks @pcuenca,

I got 1.5 from the AppStore, updated 4 days ago, which says it's got support for Stable Diffusion 3 Medium.

This git repo looks older.

Clicking App Support brings me here.

Not sure what I can do with that PR to be honest.

![diffusers-1 5](https://github.com/huggingface/swift-coreml-diffusers/assets/8770303/36699b68-1079-426d-9b2f-a59a6e67b65a)

**Comment by pcuenca** [comment]
Not sure what you need. If you want to run the app, you can do it from the App Store. If you want to build it and/or make modifications, you can clone this repo and run from that branch. Or you can just wait for it to be merged on the main branch, which should happen soon (possibly tomorrow).

**Comment by opkins** [comment]
When an app on the AppStore says "support for Stable Diffusion 3 Medium" but turns out not to have any way to install or use Stable Diffusion 3 Medium, I'm thinking that's an issue right?

Yeah, of course, I could build it and make modifications but that does fix the fact that the app on the store says it does something that it doesn't do, does it?

I'm looking for the app to do what it says it does, I'm not really up for cloning or merging as it kinda defeats the object of the simple app ease of use promise.

Perhaps the App Support button on the AppStore shouldn't link here.

I'll just wait until the app on the store actually supports SD3.

Thanks for your help.

**Comment by ZachNagengast** [comment]
Understood, can you also share a screenshot of your computer type: Click apple icon at top left -> Click "About This Mac"

**Comment by opkins** [comment]
![about-mac](https://github.com/huggingface/swift-coreml-diffusers/assets/8770303/19d8a4db-898f-4384-8853-e3ebc6786e95)

**Comment by ZachNagengast** [comment]
Thank you, that is certainly quite strange. SD3 requires > macOS 14 to run, so you should see it in the list if you update. My best guess is that this is an artifact of the [macOS check](https://github.com/huggingface/swift-coreml-diffusers/blob/17ee716c8e2ac006a48403358181d6ab24302133/Diffusion/DiffusionApp.swift#L20) on macOS 13, which is making the app think you are running on an iPhone where only smaller models are supported.

**Comment by opkins** [comment]
I've updated to macOS 14 and can confirm that I can now see the list of models you've shown above.

That's great! Thank you for your help : ]

**Comment by pcuenca** [comment]
Thanks a lot for your help @ZachNagengast 🙌! Glad everything is resolved! Closing the issue then :)
